version: '3.6'
services: 
    db:
        image: mysql:5.7.42
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment: 
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: mydb
            MYSQL_USER: user
            MYSQL_PASSWORD: user
        ports:
            - 52000:3306
        volumes: 
            - ./data-scripts:/docker-entrypoint-initdb.d
            - ./persistence:/var/lib/mysql